version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/frontend
      - build_folder:/app/dist
    command: ["npm", "run", "dev"]
    tty: true
    stdin_open: true
    restart: always
    networks:
      - camme

  database:
    container_name: database
    image: mysql:8.0
    env_file:
      - ./Backend/.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    networks:
      - camme

  backend:
    container_name: backend
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - database
    tty: true
    networks:
      - camme
    command: ["/usr/wait-for-it.sh", "database:3306", "--", "npm", "start"]

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - build_folder:/var/www/frontend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - camme

networks:
  camme:
    driver: bridge

volumes:
  build_folder:
